#!/usr/bin/env bash
# Regenerate _brand_fonts.css and _brand_logo.svg from the bundled assets.
# Run after changing any file in fonts/ or logo-white.svg.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
b64() { base64 -i "$1" | tr -d '\n'; }

cat > "$HERE/_brand_fonts.css" <<EOF
/* Auto-generated by build-snippets.sh. Do not edit. */
@font-face { font-family: 'Texta'; font-weight: 400; font-display: swap;
  src: url(data:font/woff2;base64,$(b64 "$HERE/fonts/Texta.woff2")) format('woff2'); }
@font-face { font-family: 'Texta'; font-weight: 800; font-display: swap;
  src: url(data:font/woff2;base64,$(b64 "$HERE/fonts/Texta-Bold.woff2")) format('woff2'); }
@font-face { font-family: 'Lato'; font-weight: 400; font-display: swap;
  src: url(data:font/woff2;base64,$(b64 "$HERE/fonts/Lato-Regular.woff2")) format('woff2'); }
@font-face { font-family: 'Lato'; font-weight: 700; font-display: swap;
  src: url(data:font/woff2;base64,$(b64 "$HERE/fonts/Lato-Bold.woff2")) format('woff2'); }
@font-face { font-family: 'Source Code Pro'; font-weight: 400; font-display: swap;
  src: url(data:font/woff2;base64,$(b64 "$HERE/fonts/SourceCodePro-Regular.woff2")) format('woff2'); }
EOF

cp "$HERE/logo-white.svg" "$HERE/_brand_logo.svg"

b64 "$HERE/favicon.ico" > "$HERE/_brand_favicon.b64"

echo "Wrote _brand_fonts.css ($(wc -c < "$HERE/_brand_fonts.css") bytes)"
echo "Wrote _brand_logo.svg ($(wc -c < "$HERE/_brand_logo.svg") bytes)"
echo "Wrote _brand_favicon.b64 ($(wc -c < "$HERE/_brand_favicon.b64") bytes)"
